[package]
name = "kafka-rs"
version = "0.1.0"
authors = ["Leroux Romain <leroux.rgd@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
kafka-protocol = { path = "../kafka-protocol" }
serde = "1.0"