[package]
name = "spec-parser"
version = "0.1.0"
authors = ["Leroux Romain <leroux.rgd@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
failure = "0.1"
heck = "0.3"
lazy_static = "1.2"
pest = "2.0"
pest_derive = "2.0"
regex = "1"
tera = "0.11"
